# Generated by Django 3.2.10 on 2022-02-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Programming', 'Programming'), ('others', 'others')], max_length=100),
        ),
    ]
